name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  buildAndPushDockerImage:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USR }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        tags:
          ${{ github.repository }}:latest